config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
  path("<int:pk>", views.ReviewBookListView, name="book_list"),
  path("<int:pk>", views.ReviewMovieListView, name="movie_list"),
  path("add/<int:pk>",views.add_review_book,name="book_add"),
  path("add/<int:pk>",views.add_review_movie,name="movie_add"),
  path("remove/<int:pk>",views.delete_review,name="remove"),
]

reviews/models.py
from django.db import models
from core.models import CoreModel

class Review(CoreModel):

  """ Review Model """ 

  created_by = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name="reviews",null=True,blank=True)
  text = models.TextField()
  movie = models.ForeignKey("movies.Movie", on_delete=models.CASCADE, related_name="reviews", null=True, blank=True)
  book = models.ForeignKey("books.Book", on_delete=models.CASCADE, related_name="reviews", null=True, blank=True)
  rating = models.IntegerField()

  def __str__(self):
    return self.text

reviews/forms.py
from django import forms
from . import models


class CreateReview(forms.ModelForm):
    text = forms.TextInput()
    rating = forms.IntegerField(max_value=5, min_value=1)
    class Meta:
        model = models.Review
        fields = (
            "text",
            "rating"
        )

    def save(self):
        review = super().save(commit=False)
        return review

reviews/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from . import forms
from .models import Review
from books.models import Book
from movies.models import Movie


def add_review_book(request, pk):
  user = request.user
  if user.is_authenticated:
    form = forms.CreateReview(request.POST)
    try:
      book = Book.objects.get(pk=pk)
      if form.is_valid():
        review = form.save()
        review.book = book
        review.created_by = user
        review.save()
        return redirect(reverse("core:home"))
      else:
        return redirect(reverse("core:home"))
    except Book.DoesNotExist:
      return redirect(reverse("core:home"))
  return redirect(reverse("core:home"))

def add_review_movie(request, pk):
  user = request.user
  if user.is_authenticated:
    form = forms.CreateReview(request.POST)
    try:
      movie = Movie.objects.get(pk=pk)
      if form.is_valid():
        review = form.save()
        review.movie = movie
        review.created_by = user
        review.save()
        return redirect(reverse("core:home"))
      else:
        return redirect(reverse("core:home"))
    except Movie.DoesNotExist:
      return redirect(reverse("core:home"))
  return redirect(reverse("core:home"))

def delete_review(request,pk):
  review = Review.objects.get(pk=pk)
  review.delete()
  return redirect(reverse("core:home"))

def ReviewBookListView(request,pk):
  book = Book.objects.get(pk=pk)
  reviews = Review.objects.filter(book__pk=pk)
  form = forms.CreateReview()
  return render(request,"reviews/review_book_list.html",{"reviews":reviews,"book":book,"form":form})

def ReviewMovieListView(request,pk):
  movie = Movie.objects.get(pk=pk)
  reviews = Review.objects.filter(movie__pk=pk)
  form = forms.CreateReview()
  return render(request,"reviews/review_movie_list.html",{"reviews":reviews,"movie":movie,"form":form})

templates/reviews/review_book_list.html
{% extends "base.html" %}

{% block page_title %}
  {{book.title}} Reviews
{% endblock page_title %}

{% block content %}
<div class="px-5">
  <h2 class="ml-1 text-4xl text-blue-600">{{book.title}}</h2>
  <h2 class="ml-1 text-3xl text-blue-600">Reviews</h2>
 <div class="grid my-5 grid-cols-4 gap-10">
   <h4 class="ml-1 text-gray-600">Writing</h4>
  <h4 class="ml-1 text-gray-600">User</h4>
    <h4 class="ml-1 text-gray-600">Rating</h4>
    <h4 class="ml-1 text-gray-600">Time</h4>
 </div>
	{% for r in reviews %}
    <div class="grid my-5 grid-cols-4 gap-10">
    <h4 class="ml-1 text-gray-600">{{r.text}}</h4>
    <h2 class="ml-10 text-sm text-gray-600">{{r.created_by}}</h2>
    <h2 class="ml-10 text-sm text-gray-600">{{r.rating}}</h2>
    <h2 class="ml-10 text-sm text-gray-600">{{r.created_at}}</h2>
      </div>
    {%if user.pk == r.created_by.pk%}
    <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-2 py-2 px-4 rounded w-full" href="{%url 'reviews:remove' r.pk%}">delete review</a>
    {%endif%}
	{% endfor %}
<div class="flex items-center text-center justify-center" >
  <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" action="{%url 'reviews:book_add' book.pk %}" method="POST" class="w-1/2 mx-auto">
    {%csrf_token%}
    <h5>{{form}}</h5>
  <button class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-2 py-2 px-4 rounded w-full">Submit Review</button>
  </form>  
</div>
{% endblock content %}

templates/reviews/review_movie_list.html
{% extends "base.html" %}

{% block page_title %}
  {{movie.title}} Reviews
{% endblock page_title %}

{% block content %}
<div class="px-5">
  <h2 class="ml-1 text-4xl text-blue-600">{{movie.title}}</h2>
  <h2 class="ml-1 text-3xl text-blue-600">Reviews</h2>
 <div class="grid my-5 grid-cols-4 gap-10">
   <h4 class="ml-1 text-gray-600">Writing</h4>
  <h4 class="ml-1 text-gray-600">User</h4>
    <h4 class="ml-1 text-gray-600">Rating</h4>
    <h4 class="ml-1 text-gray-600">Time</h4>
 </div>
	{% for r in reviews %}
    <div class="grid my-5 grid-cols-4 gap-10">
    <h4 class="ml-1 text-gray-600">{{r.text}}</h4>
    <h2 class="ml-10 text-sm text-gray-600">{{r.created_by}}</h2>
    <h2 class="ml-10 text-sm text-gray-600">{{r.rating}}</h2>
    <h2 class="ml-10 text-sm text-gray-600">{{r.created_at}}</h2>
      </div>
    {%if user.pk == r.created_by.pk%}
    <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-2 py-2 px-4 rounded w-full" href="{%url 'reviews:remove' r.pk%}">delete review</a>
    {%endif%}
	{% endfor %}
<div class="flex items-center text-center justify-center" >
  <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" action="{%url 'reviews:movie_add' movie.pk %}" method="POST" class="w-1/2 mx-auto">
    {%csrf_token%}
    <h5>{{form}}</h5>
  <button class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-2 py-2 px-4 rounded w-full">Submit Review</button>
  </form>  
</div>
{% endblock content %}